### ISSUE TITLE
vertical-stack-in-card TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by shreram** [thomasloven/lovelace-card-tools#25]
I am not sure if this issue belongs to this card.

Here is the error message 

```
vertical-stack-in-card TypeError: Cannot read property 'startsWith' of undefined
card-tools.js?track=true:102
    at vertical-stack-in-card.js?v=v0.1.1:76
    at Array.forEach (<anonymous>)
    at HTMLElement.setConfig (vertical-stack-in-card.js?v=v0.1.1:73)
    at _createThing (card-tools.js?track=true:100)
    at Function.createThing (card-tools.js?track=true:130)
    at Function.createCard (card-tools.js?track=true:151)
    at layout-card.js?track=true:82
    at Array.map (<anonymous>)
    at HTMLElement.make_cards (layout-card.js?track=true:80)
    at HTMLElement.setConfig (layout-card.js?track=true:16)
```

This error shows up only when I use 'break' along with 'custom:layout-card'

```
            type: custom:layout-card
            layout: auto
            cards:
              - type: custom:vertical-stack-in-card
                cards:
                  - type: glance
                    title: Switches
                    columns: 3
                    entities:
                      - type: entity-button
                        entity: switch.ge_12722_onoff_relay_switch_switch_3
                        <<: *tap_hold_anchor
                      - type: entity-button
                        entity: switch.ge_12722_onoff_relay_switch_switch_2
                        <<: *tap_hold_anchor
                      - type: entity-button
                        entity: switch.ge_12722_onoff_relay_switch_switch_4
                        <<: *tap_hold_anchor
                      - type: entity-button
                        entity: switch.leviton_dzs151lz_switch_switch
                        <<: *tap_hold_anchor
                      - type: entity-button
                        entity: switch.ge_12722_onoff_relay_switch_switch
                        <<: *tap_hold_anchor
                  - type: custom:card-modder
                    style:
                      background-color: rgb(254, 239, 179)
                      background-size: 100% 100%
                      border-radius: 10px
                      border: solid 1.5px rgb(230, 138, 0)
                      box-shadow: rgb(136, 136, 136) 2px 2px 1px 0px
                      color: rgb(230, 138, 0)
                    card:
                      type: custom:vertical-stack-in-card
                      cards:
                        - type: glance
                          title: Switches2
                          columns: 3
                          entities:
                            - type: entity-button
                              entity: switch.ge_12722_onoff_relay_switch_switch_3
                              <<: *tap_hold_anchor
                            - type: entity-button
                              entity: switch.ge_12722_onoff_relay_switch_switch_2
                              <<: *tap_hold_anchor
                            - type: entity-button
                              entity: switch.ge_12722_onoff_relay_switch_switch_4
                              <<: *tap_hold_anchor
                            - type: entity-button
                              entity: switch.leviton_dzs151lz_switch_switch
                              <<: *tap_hold_anchor
                            - type: entity-button
                              entity: switch.ge_12722_onoff_relay_switch_switch
                              <<: *tap_hold_anchor
                            - entity: light.steps_light
                              icon: mdi:stairs
                              secondary_info: last-changed
                              name: Staircase light
                  - type: entities
                    title: Lights
                    show_header_toggle: false
                    entities:
                      - entity: light.hallway_light_bulb_one
                        secondary_info: last-changed
                        name: Hallway light One
                      - entity: light.notused_light
                        secondary_info: last-changed
                        name: Hallway light Two
                      - entity: light.kids_bedroom_bulb
                        secondary_info: last-changed
                      - entity: light.steps_light
                        icon: mdi:stairs
                        secondary_info: last-changed
                        name: Staircase light
                      - entity: light.garage_light
                        secondary_info: last-changed
                  - break
```
