### ISSUE TITLE
Pop up cards not working with v2

### ISSUE THREAD

**Issue by holdestmade** [thomasloven/lovelace-card-tools#37]
After installing v2, popup cards fails and get this error in the log:

`http://xxxxxx:8123/community_plugin/lovelace-popup-card/popup-card.js:15:17 Uncaught TypeError: cardTools.logger is not a function`

If I revert to 0.4.2 it works fine

I know popup cards is deprecated but still like the way it works compared to browser mod (If i have 2 browser windows open, 1 GUI and 1 Visual Studio Code the pop up pops up oin the wrong browser)

**Comment by holdestmade** [comment]
Version 2.1 fixes this, thanks

**Comment by holdestmade** [comment]
Spoke too soon, after a browser refresh now get a Red bar at the bottom of the custom popup card
With v2.0 I got the standard Lovelace more info popup

**Comment by thomasloven** [comment]
Please provide your browser log and configuration.

**Comment by holdestmade** [comment]
See attached config and screenshots:

0.4.2
![v0 4 2](https://user-images.githubusercontent.com/13977244/68682968-e62c9400-055d-11ea-8f4f-9d063f79d66f.jpg)

2.2
![v2 2](https://user-images.githubusercontent.com/13977244/68682973-e88eee00-055d-11ea-998b-423f1386fdd3.jpg)


```
sensor.front_garden_lights_status:
  title: Front Garden Lights
  card:
      type: custom:vertical-stack-in-card
      cards:
        - type: custom:light-entity-card
          entity: light.front_garden
          color_picker: false
          persist_features: true
          full_width_sliders: true
          show_slider_percent: true
        - type: entities
          entities:
            - entity: input_boolean.front_garden_100
              name: Automation Override
            - type: custom:rgb-light-card
              entity: light.front_garden
              justify: between
              size: 24
              colors:
                - color_name: red
                  brightness: 255
                - color_name: orange
                  brightness: 255
                - color_name: yellow
                  brightness: 255
                - color_name: green
                  brightness: 255
                - color_name: cyan
                  brightness: 255
                - color_name: blue
                  brightness: 255
                - color_name: pink
                  brightness: 255
                - color_name: purple
                  brightness: 255
                - color_name: white
                  brightness: 255
        - type: history-graph
          entities:
            - entity: light.front_garden
```

**Comment by holdestmade** [comment]
Not sure if this is what you mean, when I right click and "inspect" on the faulty popup

```
<div>
  <style>
    app-toolbar {
      color: var(--more-info-header-color);
      background-color: var(--more-info-header-background);
    }
    .scrollable {
      overflow: auto;
      max-width: 100% !important;
    }
  </style>
  
      <app-toolbar>
        <paper-icon-button icon="hass:close" dialog-dismiss="" role="button" tabindex="0" aria-disabled="false"></paper-icon-button>
        <div class="main-title" main-title="">
          Front Garden Lights
        </div>
      </app-toolbar>
      
    <div class="scrollable" style="box-sizing: border-box; max-height: 1009px;">
      <card-maker nohass=""><!----><!----><hui-error-card></hui-error-card><!----><!----></card-maker>
    </div>
  </div>
```

**Comment by holdestmade** [comment]
Working popup:

```
<div>
    <style>
      app-toolbar {
        color: var(--more-info-header-color);
        background-color: var(--more-info-header-background);
      }
    </style>
    <app-toolbar>
      <paper-icon-button icon="hass:close" dialog-dismiss="" role="button" tabindex="0" aria-disabled="false"></paper-icon-button>
      <div class="main-title" main-title="">
        Front Garden Lights
      </div>
    </app-toolbar>
  <vertical-stack-in-card></vertical-stack-in-card></div>
```

**Comment by thomasloven** [comment]
> Not sure if this is what you mean, when I right click and "inspect" on the faulty popup

When you do that, you also get a tab called "Console". That's the browser console log.
See [this guide linked from the readme](https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins#browser-console)

**Comment by holdestmade** [comment]
```
CARD-TOOLS 2 IS INSTALLED  DeviceID: ed749960-a328653c
bar-card.js:1225 BAR-CARDVersion: 1.6.1
compact-custom-header.js:1  COMPACT-CUSTOM-HEADER      Version 1.4.5     
button-card.js:1767   BUTTON-CARD   Version 3.0.0 
dumper.js:756 Uncaught (in promise) rmark: undefinedmessage: "unacceptable kind of an object to dump [object Undefined]"name: "YAMLException"reason: "unacceptable kind of an object to dump [object Undefined]"stack: "YAMLException: unacceptable kind of an object to dump [object Undefined]↵    at Z (http://192.168.1.33:8123/frontend_latest/chunk.c6c3ddfdd942fe69060c.js:2416:193326)↵    at ee (http://192.168.1.33:8123/frontend_latest/chunk.c6c3ddfdd942fe69060c.js:2416:193917)↵    at e.exports.safeDump (http://192.168.1.33:8123/frontend_latest/chunk.c6c3ddfdd942fe69060c.js:2416:194005)↵    at HTMLElement.value (http://192.168.1.33:8123/frontend_latest/chunk.c6c3ddfdd942fe69060c.js:2502:32)↵    at HTMLElement.update (http://192.168.1.33:8123/frontend_latest/app.34e7b19f.js:2:17413)↵    at HTMLElement.performUpdate (http://192.168.1.33:8123/frontend_latest/app.34e7b19f.js:2:13216)↵    at HTMLElement._enqueueUpdate (http://192.168.1.33:8123/frontend_latest/app.34e7b19f.js:2:12846)"__proto__: Error
config-template-card.js:3218   CONFIG_TEMPLATE-CARD    Version 1.0.7         
dumper.js:756 Uncaught (in promise) rmark: undefinedmessage: "unacceptable kind of an object to dump [object Undefined]"name: "YAMLException"reason: "unacceptable kind of an object to dump [object Undefined]"stack: "YAMLException: unacceptable kind of an object to dump [object Undefined]↵    at Z (http://192.168.1.33:8123/frontend_latest/chunk.c6c3ddfdd942fe69060c.js:2416:193326)↵    at ee (http://192.168.1.33:8123/frontend_latest/chunk.c6c3ddfdd942fe69060c.js:2416:193917)↵    at e.exports.safeDump (http://192.168.1.33:8123/frontend_latest/chunk.c6c3ddfdd942fe69060c.js:2416:194005)↵    at HTMLElement.value (http://192.168.1.33:8123/frontend_latest/chunk.c6c3ddfdd942fe69060c.js:2502:32)↵    at HTMLElement.update (http://192.168.1.33:8123/frontend_latest/app.34e7b19f.js:2:17413)↵    at HTMLElement.performUpdate (http://192.168.1.33:8123/frontend_latest/app.34e7b19f.js:2:13216)↵    at HTMLElement._enqueueUpdate (http://192.168.1.33:8123/frontend_latest/app.34e7b19f.js:2:12846)"__proto__: Error
dumper.js:756 Uncaught (in promise) r {name: "YAMLException", reason: "unacceptable kind of an object to dump [object Undefined]", mark: undefined, message: "unacceptable kind of an object to dump [object Undefined]", stack: "YAMLException: unacceptable kind of an object to d….33:8123/frontend_latest/app.34e7b19f.js:2:12846)"}
_enqueueUpdate @ updating-element.js:469
async function (async)
_enqueueUpdate @ updating-element.js:446
_requestUpdate @ updating-element.js:413
initialize @ updating-element.js:268
initialize @ lit-element.js:95
O @ updating-element.js:98
V @ lit-element.js:46
F @ hui-error-card.ts:29
c @ card-tools.js:1
l @ card-tools.js:1
u @ card-tools.js:1
create @ card-tools.js:1
setConfig @ card-tools.js:1
set config @ card-tools.js:1
b @ card-tools.js:1
(anonymous) @ popup-card.js:25
r @ fire_event.ts:76
a @ handle-click.ts:57
value @ hui-image-element.ts:77
handleEvent @ parts.js:434
__boundHandleEvent @ parts.js:400
r @ long-press-directive.ts:135
dumper.js:756 Uncaught (in promise) r {name: "YAMLException", reason: "unacceptable kind of an object to dump [object Undefined]", mark: undefined, message: "unacceptable kind of an object to dump [object Undefined]", stack: "YAMLException: unacceptable kind of an object to d….33:8123/frontend_latest/app.34e7b19f.js:2:12846)"}
_enqueueUpdate @ updating-element.js:469
async function (async)
_enqueueUpdate @ updating-element.js:446
_requestUpdate @ updating-element.js:413
initialize @ updating-element.js:268
initialize @ lit-element.js:95
O @ updating-element.js:98
V @ lit-element.js:46
F @ hui-error-card.ts:29
c @ card-tools.js:1
l @ card-tools.js:1
u @ card-tools.js:1
create @ card-tools.js:1
setConfig @ card-tools.js:1
set config @ card-tools.js:1
b @ card-tools.js:1
(anonymous) @ popup-card.js:25
r @ fire_event.ts:76
a @ handle-click.ts:57
value @ hui-image-element.ts:77
handleEvent @ parts.js:434
__boundHandleEvent @ parts.js:400
r @ long-press-directive.ts:135
```

**Comment by thomasloven** [comment]
Hm...
I'm suspecting the problem actually lies elsewhere, but there's not enough evidence yet.
Please try card-tools version 2.3. That should give you a more useful error message in the red card.

**Comment by holdestmade** [comment]
See attached log with v2.3 installed:

```
dumper.js:756 Uncaught (in promise) r {name: "YAMLException", reason: "unacceptable kind of an object to dump [object HTMLElement]", mark: undefined, message: "unacceptable kind of an object to dump [object HTMLElement]", stack: "YAMLException: unacceptable kind of an object to d….33:8123/frontend_latest/app.34e7b19f.js:2:12846)"}mark: undefinedmessage: "unacceptable kind of an object to dump [object HTMLElement]"name: "YAMLException"reason: "unacceptable kind of an object to dump [object HTMLElement]"stack: "YAMLException: unacceptable kind of an object to dump [object HTMLElement]↵    at Z (http://192.168.1.33:8123/frontend_latest/chunk.c6c3ddfdd942fe69060c.js:2416:193326)↵    at ee (http://192.168.1.33:8123/frontend_latest/chunk.c6c3ddfdd942fe69060c.js:2416:193917)↵    at e.exports.safeDump (http://192.168.1.33:8123/frontend_latest/chunk.c6c3ddfdd942fe69060c.js:2416:194005)↵    at HTMLElement.value (http://192.168.1.33:8123/frontend_latest/chunk.c6c3ddfdd942fe69060c.js:2502:32)↵    at HTMLElement.update (http://192.168.1.33:8123/frontend_latest/app.34e7b19f.js:2:17413)↵    at HTMLElement.performUpdate (http://192.168.1.33:8123/frontend_latest/app.34e7b19f.js:2:13216)↵    at HTMLElement._enqueueUpdate (http://192.168.1.33:8123/frontend_latest/app.34e7b19f.js:2:12846)"__proto__: Error
_enqueueUpdate @ updating-element.js:469
async function (async)
_enqueueUpdate @ updating-element.js:446
_requestUpdate @ updating-element.js:413
initialize @ updating-element.js:268
initialize @ lit-element.js:95
O @ updating-element.js:98
V @ lit-element.js:46
F @ hui-error-card.ts:29
c @ card-tools.js:1
l @ card-tools.js:1
u @ card-tools.js:1
create @ card-tools.js:1
setConfig @ card-tools.js:1
set config @ card-tools.js:1
S @ card-tools.js:1
(anonymous) @ popup-card.js:25
r @ fire_event.ts:76
a @ handle-click.ts:57
value @ hui-image-element.ts:77
handleEvent @ parts.js:434
__boundHandleEvent @ parts.js:400
r @ long-press-directive.ts:135

```

**Comment by holdestmade** [comment]
Also, on browser refresh with 0.4.2 installed, get this:

```
card-tools.js:425 CARD-TOOLS IS INSTALLEDDeviceID: ed749960-a328653c
bar-card.js:1225 BAR-CARDVersion: 1.6.1
compact-custom-header.js:1  COMPACT-CUSTOM-HEADER      Version 1.4.5     
button-card.js:1767   BUTTON-CARD   Version 3.0.0 
dumper.js:756 Uncaught (in promise) r {name: "YAMLException", reason: "unacceptable kind of an object to dump [object Undefined]", mark: undefined, message: "unacceptable kind of an object to dump [object Undefined]", stack: "YAMLException: unacceptable kind of an object to d….33:8123/frontend_latest/app.34e7b19f.js:2:12846)"}
Promise.then (async)
(anonymous) @ vertical-stack-in-card.js:122
connectedCallback @ vertical-stack-in-card.js:116
_rebuildCard @ hui-stack-card.ts:97
t.addEventListener.once @ hui-stack-card.ts:85
r @ fire_event.ts:76
(anonymous) @ create-card-element.ts:111
Promise.then (async)
ya @ create-card-element.ts:109
_createCardElement @ hui-stack-card.ts:77
(anonymous) @ hui-stack-card.ts:39
setConfig @ hui-stack-card.ts:38
fa @ create-card-element.ts:73
ya @ create-card-element.ts:124
value @ hui-view.ts:60
(anonymous) @ hui-view.ts:286
value @ hui-view.ts:285
value @ hui-view.ts:214
performUpdate @ updating-element.js:526
_enqueueUpdate @ updating-element.js:460
async function (async)
_enqueueUpdate @ updating-element.js:446
_requestUpdate @ updating-element.js:413
initialize @ updating-element.js:268
initialize @ lit-element.js:95
O @ updating-element.js:98
V @ lit-element.js:46
r @ hui-view.ts:50
value @ hui-root.ts:652
(anonymous) @ hui-root.ts:492
setTimeout (async)
(anonymous) @ render-status.ts:2
(anonymous) @ web-animations-next-lite.min.js:15
requestAnimationFrame (async)
window.requestAnimationFrame @ web-animations-next-lite.min.js:15
r @ render-status.ts:2
value @ hui-root.ts:492
performUpdate @ updating-element.js:526
_enqueueUpdate @ updating-element.js:460
async function (async)
_enqueueUpdate @ updating-element.js:446
_requestUpdate @ updating-element.js:413
initialize @ updating-element.js:268
initialize @ lit-element.js:95
O @ updating-element.js:98
V @ lit-element.js:46
r @ hui-root.ts:66
_clone @ template-instance.js:84
__commitTemplateResult @ parts.js:244
commit @ parts.js:186
s @ render.js:44
V.render @ shady-render.js:251
update @ lit-element.js:166
performUpdate @ updating-element.js:508
_enqueueUpdate @ updating-element.js:460
async function (async)
_enqueueUpdate @ updating-element.js:446
_requestUpdate @ updating-element.js:413
set @ updating-element.js:166
value @ ha-panel-lovelace.ts:179
value @ ha-panel-lovelace.ts:143
performUpdate @ updating-element.js:524
_enqueueUpdate @ updating-element.js:460
async function (async)
_enqueueUpdate @ updating-element.js:446
_requestUpdate @ updating-element.js:413
initialize @ updating-element.js:268
initialize @ lit-element.js:95
O @ updating-element.js:98
V @ lit-element.js:46
o @ ha-panel-lovelace.ts:55
value @ hass-router-page.ts:271
value @ hass-router-page.ts:291
_currentLoadProm.c.then._currentLoadProm @ hass-router-page.ts:197
Promise.then (async)
value @ hass-router-page.ts:188
performUpdate @ updating-element.js:508
_enqueueUpdate @ updating-element.js:460
async function (async)
_enqueueUpdate @ updating-element.js:446
_requestUpdate @ updating-element.js:413
set @ updating-element.js:166
value @ hass-router-page.ts:259
async function (async)
value @ hass-router-page.ts:256
value @ partial-panel-resolver.ts:115
value @ partial-panel-resolver.ts:82
performUpdate @ updating-element.js:526
_enqueueUpdate @ updating-element.js:460
async function (async)
_enqueueUpdate @ updating-element.js:446
_requestUpdate @ updating-element.js:413
initialize @ updating-element.js:268
O @ updating-element.js:98
n @ hass-router-page.ts:49
n @ partial-panel-resolver.ts:65
_clone @ template-instance.js:84
__commitTemplateResult @ parts.js:244
commit @ parts.js:186
s @ render.js:44
V.render @ shady-render.js:251
update @ lit-element.js:166
performUpdate @ updating-element.js:508
_enqueueUpdate @ updating-element.js:460
async function (async)
_enqueueUpdate @ updating-element.js:446
_requestUpdate @ updating-element.js:413
initialize @ updating-element.js:268
initialize @ lit-element.js:95
O @ updating-element.js:98
V @ lit-element.js:46
r @ home-assistant-main.ts:36
_clone @ template-instance.js:84
__commitTemplateResult @ parts.js:244
commit @ parts.js:186
update @ template-instance.js:40
__commitTemplateResult @ parts.js:236
commit @ parts.js:186
s @ render.js:44
V.render @ shady-render.js:251
update @ lit-element.js:166
performUpdate @ updating-element.js:508
_enqueueUpdate @ updating-element.js:460
async function (async)
_enqueueUpdate @ updating-element.js:446
_requestUpdate @ updating-element.js:413
set @ updating-element.js:166
value @ hass-base-mixin.ts:49
(anonymous) @ connection-mixin.ts:137
n @ haws.es.js:1
(anonymous) @ haws.es.js:1
Promise.then (async)
c @ haws.es.js:1
u @ haws.es.js:1
subscribe @ haws.es.js:1
S @ haws.es.js:1
(anonymous) @ core.ts:77
Promise.then (async)
166 @ core.ts:71
o @ bootstrap:63
(anonymous) @ bootstrap:198
(anonymous) @ bootstrap:198
config-template-card.js:3218   CONFIG_TEMPLATE-CARD    Version 1.0.7         

```

**Comment by thomasloven** [comment]
The last one, at least, is caused by vertical-stack-in-card. It has the same bug as card-tools did before 2.3. I've contacted the developer.

**Comment by thomasloven** [comment]
Perhaps you could try the following?
- Open the inspector to the faulty popup, 
- Click `<hui-error-card>` to select it
- Go to the console
- type `$0._config` and press enter

You should get something like this:
![image](https://user-images.githubusercontent.com/1299821/68759942-00737a00-0611-11ea-92a3-987a0b8a7b49.png)

**Comment by holdestmade** [comment]
I changed the vertical stack in card to normal vertical stack and same error

**Comment by thomasloven** [comment]
Oh!

Did you get the latest version of popup-card?
https://github.com/thomasloven/lovelace-popup-card

I snuck in a change for it to work with the new card tools a few days ago, and forgot about it...

**Comment by holdestmade** [comment]
Ah, that seems to have sorted it, many thanks for all you time

**Comment by thomasloven** [comment]
Great!
Sorry for the trouble with me forgetting about that...

**Comment by holdestmade** [comment]
No problem, I have come used to using HACS for everything and totally slipped my mind to check this

**Comment by Oriondely** [comment]
Hi all, I have a very similar issue and i don't know how to fix it.
Using the previous lovelace custom components all was working good on android and PC (chrome/edge browsers), but I had issues on popup-cards with iPad (safari/edge/chrome browsers): entities are shown twice in popup cards, and popup cards are not scrollable.

So I tried to update "card-tools", "popup-card" and "more-info-card" to the latest version, but now I'm not able to see anymore popup-cards on my HA page. 

I have this error when HA starts:
_2020-08-16 14:50:18 ERROR (MainThread) [frontend.js.latest.201910022] http://192.168.2.6:8123/local/more-info-card/more-info-card.js?v=202008161449:1:1713 Uncaught NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "more-info-card" has already been used with this registry_

And this one when a popup-card is called (is it shown the standard more-info one instead, when I press on the entity):
_2020-08-16 14:52:24 ERROR (MainThread) [frontend.js.latest.201910022] http://192.168.2.6:8123/local/popup-card/popup-card.js?v=202008161449:8:30 Uncaught TypeError: moreInfo.getAttribute is not a function_

Home Assistant version: 0.100.2
iOS version: 13.6

**ui-lovelace.yaml**

```
resources:
  - url: /local/card-tools/card-tools.js?v=202008161449
    type: js
  - url: /local/more-info-card/more-info-card.js?v=202008161449
    type: js
  - url: /local/popup-card/popup-card.js?v=202008161449
    type: js    
  - url: /local/fold-entity-row/fold-entity-row.js
    type: js
  - url: /local/card-modder/card-modder.js
    type: js
  - url: /local/time-input-row/time-input-row.js
    type: js
  - url: /local/dual-gauge-card/dual-gauge-card.js
    type: js
  - url: /local/vertical-stack-in-card/vertical-stack-in-card.js?v=0.1.2
    type: js
  - url: /local/bar-card/bar-card.js?v=1.0.0
    type: js
  - url: /local/mini-graph-card-bundle/mini-graph-card-bundle.js?v=0.4.3
    type: js
  - url: /local/slider-entity-row/slider-entity-row.js
    type: js
  - url: /local/button-card/button-card.js
    type: js
  - url: /local/mini-media-player-bundle/mini-media-player-bundle.js?v=1.4.1
    type: js

views:
  - title: Zona Giorno
    icon: 'mdi:weather-sunny'
    panel: false
    path: default_view
    badges: []
    popup_cards:
      light.01_ingresso_1_corridoio:
        title: Luci 01 Ingresso
        large: true
        card:
          type: entities
          show_header_toggle: false
          entities:
            - type: custom:more-info-card
              entity: light.01_ingresso_1_corridoio
            - type: custom:more-info-card
              entity: light.01_ingresso_2_zona_giorno
            - type: custom:more-info-card
              entity: light.01_ingresso_3_zona_notte

    cards:
      - type: custom:vertical-stack-in-card
        title: Ingresso
        cards:
        - type: glance
          columns: 1
          show_icon: true
          show_name: false
          show_state: true
          entities:
            - entity: light.01_ingresso_1_corridoio
```

What can I do?
Thank you.
