### ISSUE TITLE
Cast issue with secondaryinfo-entity-row

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-card-tools#39]
As issued on https://github.com/custom-cards/secondaryinfo-entity-row/issues/15 could it be card-tools creates an issue here?

Casting a fine working card results in 'cant find card-tools' and direct us to your GitHub 

```
  - type: custom:vertical-stack-in-card
    title: Boiler switch monitor
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - type: 'custom:secondaryinfo-entity-row'
            entity: switch.sw_boiler_bijkeuken_template
            secondary_info: 'Actueel verbruik: [[ sensor.boiler_bijkeuken_actueel ]] watt'
          - input_number.zp_opbrengst_threshold
          - sensor.zp_actuele_opbrengst
```
please have a look, thanks!
